import type { Product } from "./types"

export const initialProducts: Product[] = [
  // Promos
  {
    id: "promo-001",
    name: "Kit Iniciante Completo",
    description: "Paquete promocional: Calabaza natural + Bombilla alpaca + Yerba Mate 1kg. Precio especial por tiempo limitado.",
    price: 59.99,
    image: "/images/kit-matero.jpg",
    category: "promos",
    stock: 15,
    featured: true,
  },
  {
    id: "promo-002",
    name: "Combo Termos + Yerba",
    description: "Combo especial: Termo Stanley 1L + Yerba Mate Tradicional 1kg. Todo lo que necesitas para empezar.",
    price: 54.99,
    image: "/images/kit-matero.jpg",
    category: "promos",
    stock: 10,
    featured: true,
  },

  // Mates Imperiales
  {
    id: "mate-imperial-001",
    name: "Mate Imperial de Madera Premium",
    description: "Mate imperial de madera de alta calidad con detalle en plata. Diseño elegante y duradero.",
    price: 45.99,
    image: "/images/mate-madera.jpg",
    category: "mates",
    subcategory: "mates-imperiales",
    stock: 8,
    featured: true,
  },
  {
    id: "mate-imperial-002",
    name: "Mate Imperial de Cerámica Artesanal",
    description: "Mate imperial hecho a mano con diseños tradicionales únicos. Cada pieza es especial.",
    price: 49.99,
    image: "/images/mate-ceramica.jpg",
    category: "mates",
    subcategory: "mates-imperiales",
    stock: 6,
  },
  {
    id: "mate-imperial-003",
    name: "Mate Imperial de Cuero Labrado",
    description: "Mate imperial con cuero labrado artesanalmente. Lujo y tradición combinados.",
    price: 55.99,
    image: "/images/calabaza-natural.jpg",
    category: "mates",
    subcategory: "mates-imperiales",
    stock: 5,
  },

  // Mates Tradicionales
  {
    id: "mate-tradicion-001",
    name: "Calabaza Natural Tradicional",
    description: "Calabaza natural hecha a mano con borde de cuero. El mate clásico por excelencia.",
    price: 24.99,
    image: "/images/calabaza-natural.jpg",
    category: "mates",
    subcategory: "mates-tradicionales",
    stock: 15,
    featured: true,
  },
  {
    id: "mate-tradicion-002",
    name: "Mate de Vidrio con Funda de Cuero",
    description: "Mate de vidrio moderno con funda protectora de cuero. Fácil de limpiar y mantener.",
    price: 19.99,
    image: "/images/mate-vidrio.jpg",
    category: "mates",
    subcategory: "mates-tradicionales",
    stock: 20,
  },
  {
    id: "mate-tradicion-003",
    name: "Mate de Cerámica Pintado",
    description: "Mate de cerámica artesanal pintado a mano con motivos tradicionales.",
    price: 29.99,
    image: "/images/mate-ceramica.jpg",
    category: "mates",
    subcategory: "mates-tradicionales",
    stock: 10,
  },
  {
    id: "mate-tradicion-004",
    name: "Mate de Madera Oscura",
    description: "Mate de madera oscura pulida. Acabado liso y cómodo de sostener.",
    price: 22.99,
    image: "/images/mate-madera.jpg",
    category: "mates",
    subcategory: "mates-tradicionales",
    stock: 12,
  },

  // Mates Torpedos
  {
    id: "mate-torpedo-001",
    name: "Mate Torpedo Clásico",
    description: "Forma torpedo clásica de calabaza natural. Ergonómico y auténtico.",
    price: 26.99,
    image: "/images/calabaza-natural.jpg",
    category: "mates",
    subcategory: "mates-torpedos",
    stock: 18,
    featured: true,
  },
  {
    id: "mate-torpedo-002",
    name: "Mate Torpedo de Vidrio Templado",
    description: "Mate torpedo en vidrio templado con protección térmica. Moderno y resistente.",
    price: 32.99,
    image: "/images/mate-vidrio.jpg",
    category: "mates",
    subcategory: "mates-torpedos",
    stock: 14,
  },
  {
    id: "mate-torpedo-003",
    name: "Mate Torpedo de Cerámica",
    description: "Forma torpedo en cerámica artesanal. Tradicional y elegante.",
    price: 35.99,
    image: "/images/mate-ceramica.jpg",
    category: "mates",
    subcategory: "mates-torpedos",
    stock: 9,
  },

  // Materas
  {
    id: "matera-001",
    name: "Bolsa Matera Térmica",
    description: "Bolsa térmica para llevar tu mate. Espacio para mate, thermos y accesorios.",
    price: 34.99,
    image: "/images/bolsa-matera.jpg",
    category: "materas",
    stock: 12,
    featured: true,
  },
  {
    id: "matera-002",
    name: "Bolsa Matera de Cuero",
    description: "Bolsa de cuero auténtico para mate set. Clásica y duradera.",
    price: 44.99,
    image: "/images/bolsa-matera.jpg",
    category: "materas",
    stock: 8,
  },
  {
    id: "matera-003",
    name: "Bolsa Matera Deportiva",
    description: "Bolsa deportiva con correa ajustable. Perfecta para llevar mate a cualquier lado.",
    price: 29.99,
    image: "/images/bolsa-matera.jpg",
    category: "materas",
    stock: 16,
  },

  // Yerberos
  {
    id: "yerbero-001",
    name: "Yerbero de Cuero Marrón",
    description: "Contenedor de cuero para yerba. Mantiene la yerba fresca y es portátil.",
    price: 22.99,
    image: "/images/yerbera-cuero.jpg",
    category: "yerberos",
    stock: 15,
    featured: true,
  },
  {
    id: "yerbero-002",
    name: "Yerbero de Cuero Negro",
    description: "Yerbero de cuero premium en color negro. Elegante y funcional.",
    price: 26.99,
    image: "/images/yerbera-cuero.jpg",
    category: "yerberos",
    stock: 12,
  },
  {
    id: "yerbero-003",
    name: "Yerbero Estanco de Plástico",
    description: "Contenedor estanco de plástico resistente. Protege la yerba del aire y la humedad.",
    price: 16.99,
    image: "/images/yerbera-cuero.jpg",
    category: "yerberos",
    stock: 20,
  },

  // Termos
  {
    id: "termo-001",
    name: "Termo Stanley 1L Verde",
    description: "Termo Stanley clásico de 1 litro. Mantiene el agua caliente más de 24 horas.",
    price: 49.99,
    image: "/images/termo-stanley.jpg",
    category: "termos",
    stock: 12,
    featured: true,
  },
  {
    id: "termo-002",
    name: "Termo Lumilagro 1L Plateado",
    description: "Termo argentino Lumilagro de 1 litro. Buena relación precio-calidad.",
    price: 34.99,
    image: "/images/termo-lumilagro.jpg",
    category: "termos",
    stock: 18,
  },
  {
    id: "termo-003",
    name: "Termo Matero con Pico Cebador",
    description: "Termo diseñado especialmente para mate. Pico vertedor de precisión.",
    price: 39.99,
    image: "/images/termo-matero.jpg",
    category: "termos",
    stock: 15,
  },
  {
    id: "termo-004",
    name: "Termo Lumilagro 1.5L",
    description: "Termo grande Lumilagro de 1.5 litros. Para sesiones largas de mate.",
    price: 44.99,
    image: "/images/termo-lumilagro.jpg",
    category: "termos",
    stock: 10,
  },

  // Bombillas
  {
    id: "bombilla-001",
    name: "Bombilla Alpaca Clásica",
    description: "Bombilla de alpaca plateada tradicional. Filtro fino y duradero.",
    price: 14.99,
    image: "/images/bombilla-alpaca.jpg",
    category: "bombillas",
    stock: 30,
    featured: true,
  },
  {
    id: "bombilla-002",
    name: "Bombilla Acero Inoxidable",
    description: "Bombilla moderna de acero inoxidable. Higiénica y fácil de limpiar.",
    price: 9.99,
    image: "/images/bombilla-acero.jpg",
    category: "bombillas",
    stock: 40,
  },
  {
    id: "bombilla-003",
    name: "Bombilla con Resorte",
    description: "Bombilla con sistema de resorte. Evita atascos con cualquier tipo de yerba.",
    price: 12.99,
    image: "/images/bombilla-resorte.jpg",
    category: "bombillas",
    stock: 25,
  },
  {
    id: "bombilla-004",
    name: "Set de 3 Bombillas Acero",
    description: "Pack de 3 bombillas de acero inoxidable. Diferentes estilos y tamaños.",
    price: 24.99,
    image: "/images/bombilla-set.jpg",
    category: "bombillas",
    stock: 20,
  },

  // Otros
  {
    id: "otro-001",
    name: "Cepillo Limpia Bombilla",
    description: "Cepillo especializado para limpiar bombillas. Mantiene tu sorbete higiénico.",
    price: 4.99,
    image: "/images/cepillo-bombilla.jpg",
    category: "otros",
    stock: 50,
  },
  {
    id: "otro-002",
    name: "Yerba Mate Tradicional 1kg",
    description: "Yerba mate clásica argentina con sabor equilibrado. Ideal para uso diario.",
    price: 12.99,
    image: "/images/yerba-tradicional.jpg",
    category: "otros",
    stock: 50,
    featured: true,
  },
  {
    id: "otro-003",
    name: "Yerba Mate Suave 500g",
    description: "Yerba mate suave para principiantes. Bajo amargor y aroma agradable.",
    price: 7.99,
    image: "/images/yerba-suave.jpg",
    category: "otros",
    stock: 35,
  },
  {
    id: "otro-004",
    name: "Yerba Mate Orgánica 500g",
    description: "Yerba mate certificada orgánica. Sin pesticidas, sabor puro y natural.",
    price: 11.99,
    image: "/images/yerba-organica.jpg",
    category: "otros",
    stock: 20,
  },
]
