insert into public.products (id, name, description, price, image, category, subcategory, stock, featured)
values
  ('promo-001', 'CRIOLLO + BOMBILLA + YERBERO', 'Kit promocional con mate criollo, bombilla y yerbero.', 32000, '/images/kit-matero.jpg', 'promos', null, 10, false),
  ('promo-002', 'CAMIONERO + BOMBILLA + YERBERO', 'Kit promocional con mate camionero, bombilla y yerbero.', 42000, '/images/kit-matero.jpg', 'promos', null, 10, false),
  ('promo-003', 'IMPERIAL + BOMBILLA + YERBERO', 'Kit promocional con mate imperial, bombilla y yerbero.', 52000, '/images/kit-matero.jpg', 'promos', null, 10, false),
  ('promo-004', 'COMBO SOL DE MAYO', 'Mate Sol de Mayo + Yerbero Grabado + Bombilla', 58000, '/images/kit-matero.jpg', 'promos', null, 10, false),
  ('promo-005', 'CRIOLLO + BOMBILLA + TERMO', 'Kit promocional con mate criollo, bombilla y termo.', 44000, '/images/kit-matero.jpg', 'promos', null, 10, false),
  ('promo-006', 'CAMIONERO + BOMBILLA + TERMO', 'Kit promocional con mate camionero, bombilla y termo.', 54000, '/images/kit-matero.jpg', 'promos', null, 10, false),
  ('promo-007', 'IMPERIAL + BOMBILLA + TERMO', 'Kit promocional con mate imperial, bombilla y termo.', 64000, '/images/kit-matero.jpg', 'promos', null, 10, false),
  ('promo-008', 'RANCHERO + BOMBILLA + TERMO', 'Kit promocional con mate ranchero, bombilla y termo.', 68500, '/images/kit-matero.jpg', 'promos', null, 10, false),
  ('mate-006', 'IMPERIAL', 'Virola de Alpaca Cincelada y Lisa', 38000, '/images/mate-madera.jpg', 'mates', 'mates-imperiales', 10, false),
  ('mate-002', 'IMPERIAL CUERO CRUDO', 'Virola de Alpaca', 0, '/images/mate-madera.jpg', 'mates', 'mates-imperiales', 0, false),
  ('mate-008', 'IMPERIAL ALGARROBO', 'Premium Virola de Alpaca', 40000, '/images/mate-madera.jpg', 'mates', 'mates-imperiales', 10, false),
  ('mate-011', 'IMPERIAL ALGARROBO', 'Virola de Acero Inoxidable', 14000, '/images/mate-madera.jpg', 'mates', 'mates-imperiales', 10, false),
  ('mate-001', 'SOL DE MAYO', 'Mate de Algarrobo Chapeado con el Sol', 40000, '/images/mate-madera.jpg', 'mates', 'mates-tradicionales', 10, false),
  ('mate-004', 'RANCHERO', 'Madera Maciza de Algarrobo', 42500, '/images/mate-madera.jpg', 'mates', 'mates-tradicionales', 10, false),
  ('mate-005', 'CAMIONERO', 'Virola de Acero', 27000, '/images/mate-madera.jpg', 'mates', 'mates-tradicionales', 10, false),
  ('mate-009', 'CRIOLLO', 'Mate Calabaza con Base de Cuero Coquito/SP', 16000, '/images/mate-madera.jpg', 'mates', 'mates-tradicionales', 10, false),
  ('mate-010', 'CAMIONERO ALGARROBO', 'Virola de Acero Inoxidable', 14000, '/images/mate-madera.jpg', 'mates', 'mates-tradicionales', 10, false),
  ('mate-007', 'TORPEDO', 'Virola de Acero', 27000, '/images/mate-madera.jpg', 'mates', 'mates-torpedos', 10, false),
  ('mate-003', 'TORPEDO CUERO CRUDO', 'Virola de Alpaca', 40000, '/images/mate-madera.jpg', 'mates', 'mates-torpedos', 10, false),
  ('matera-001', 'MORRAL MARRON', 'Bandolera Matera de Cuero', 85000, '/images/bolsa-matera.jpg', 'materas', null, 10, false),
  ('matera-002', 'MORRAL NEGRO', 'Bandolera Matera de Cuero', 85000, '/images/bolsa-matera.jpg', 'materas', null, 10, false),
  ('matera-003', 'CANASTA', 'Canasta Cuadra de Cuero 4x4', 0, '/images/bolsa-matera.jpg', 'materas', null, 0, false),
  ('matera-004', 'PATAGONIA', 'Matera de Tela con Cierre y Detalles de Cuero', 65000, '/images/bolsa-matera.jpg', 'materas', null, 10, false),
  ('yerbero-001', 'GAMUZADO MARRON', 'Yerbero de Cuero con Capacidad de 500g', 13000, '/images/yerbera-cuero.jpg', 'yerberos', null, 10, false),
  ('yerbero-002', 'GAMUZADO BEIGE', 'Yerbero de Cuero con Capacidad de 500g', 13000, '/images/yerbera-cuero.jpg', 'yerberos', null, 10, false),
  ('yerbero-003', 'GAMUZADO VERDE', 'Yerbero de Cuero con Capacidad de 500g', 13000, '/images/yerbera-cuero.jpg', 'yerberos', null, 10, false),
  ('yerbero-004', 'GAMUZADO CON BASE', 'Yerbero de Cuero con Capacidad de 500g', 13000, '/images/yerbera-cuero.jpg', 'yerberos', null, 10, false),
  ('sombrero-001', 'SOMBRERO NORTEÑO', 'Ala 10"', 65000, '/images/sombrero.jpg', 'otros', null, 10, false),
  ('sombrero-002', 'SOMBRERO AUSTRALIANO', 'Cuero Engrasado', 65000, '/images/sombrero.jpg', 'otros', null, 10, false),
  ('poncho-001', 'PONCHO PESADO', 'Guarda Lisa', 79000, '/images/poncho.jpg', 'otros', null, 10, false),
  ('poncho-002', 'PONCHO PESADO', 'Guarda Incaica', 79000, '/images/poncho.jpg', 'otros', null, 10, false),
  ('boina-001', 'TOLOSA DE HILO', 'Tolosa Tupida. Colores: Beige, Bordo, Gris', 35000, '/images/boina.jpg', 'otros', null, 10, false),
  ('boina-002', 'ESPINOSA DE PAÑO', 'Colores Azul, Verde, Bordo', 40000, '/images/boina.jpg', 'otros', null, 10, false),
  ('boina-003', 'ECONOMICA DE HILO', 'Colores Azul, Bordo', 10000, '/images/boina.jpg', 'otros', null, 10, false),
  ('termo-001', 'MEDIA MANIJA', 'Termo media manija clásico.', 25000, '/images/termo-stanley.jpg', 'termos', null, 10, false),
  ('termo-002', 'TERMOLAR NEGRO', 'Termo Termolar color negro.', 80000, '/images/termo-stanley.jpg', 'termos', null, 10, false),
  ('termo-003', 'STANLEY ORIGINAL', 'Termo Stanley original, alta calidad.', 125000, '/images/termo-stanley.jpg', 'termos', null, 10, false),
  ('termo-004', 'OPCIONES GRABADAS', 'Personalizadas en Termos', 5000, '/images/termo-stanley.jpg', 'termos', null, 10, false),
  ('bombilla-001', 'PICO DE ORO', 'Bombilla de Acero Inoxidable Tamaño Pequeño y Grande ($5.500 PROMO CON MATE)', 6500, '/images/bombilla-alpaca.jpg', 'bombillas', null, 10, false),
  ('bombilla-002', 'PICO DE ORO DORADA', 'Bombilla de Acero Inoxidable Tamaño Pequeño y Grande ($5.500 PROMO CON MATE)', 6500, '/images/bombilla-alpaca.jpg', 'bombillas', null, 10, false),
  ('bombilla-003', 'BOMBILLO PICO DE REY', 'Bombillo de Alpaca Liso', 10000, '/images/bombilla-alpaca.jpg', 'bombillas', null, 10, false),
  ('otro-001', 'GRABADOS', 'Virolas, Calabazas, Cueros, Termos, Bombillas, Yerberos. DONDE QUIERAS ($5.000 x1  $4.000 x2  $3.000 x3)', 5000, '/images/otros.jpg', 'otros', null, 10, false),
  ('otro-002', 'PORTAMATES', 'De Cuero. Sirve para transportar en la caja de cambio del auto', 15000, '/images/otros.jpg', 'otros', null, 10, false),
  ('otro-003', 'DESPOLVILLADORES', 'Para quitar el polvillo de la yerba', 15000, '/images/otros.jpg', 'otros', null, 10, false),
  ('otro-004', 'TABLA DE ASADO', 'Tabla de madera para asado.', 40000, '/images/otros.jpg', 'otros', null, 10, false)
on conflict (id) do update set
  name = excluded.name,
  description = excluded.description,
  price = excluded.price,
  image = excluded.image,
  category = excluded.category,
  subcategory = excluded.subcategory,
  stock = excluded.stock,
  featured = excluded.featured,
  updated_at = now();
